# version: '3.9'  ← Kannst du drin lassen oder löschen, ist egal

services:
  mrpserver:
    image: postgres:16-alpine
    container_name: mrpserver
    restart: always
    environment:
      POSTGRES_USER: mrp
      POSTGRES_PASSWORD: mrp123
      POSTGRES_DB: mrpdb
    ports:
      - "5432:5432"
    volumes:
      - mrp_data:/var/lib/postgresql/data

volumes:
  mrp_data:
